---
apiVersion: v1
kind: Secret
metadata:
  name: example-postgresql-exporter
  labels:
    name: example-postgresql-exporter
    app: postgresql
type: Opaque
data:
  data_source_name: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnNvbWUtcmFuZG9tLXBhc3N3b3JkQGVuZGdhbWUtcG9zdGdyZXNxbC5kZWZhdWx0OjU0MzIvcG9zdGdyZXM/c3NsbW9kZT1kaXNhYmxl"