apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: example-postgresql-exporter
  name: example-postgresql
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      name: example-postgresql-exporter